# Site settings
title: I'm Satomi
description: Satomi Ito Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://satomitheito.github.io"
baseurl: ""
# User settings
username: Satomi Ito
user_title: "Data Scientist"
email: si408@georgetown.edu
github_username:  satomitheito

sass:
  style: compressed

exclude: ['package.json', 'src', 'node_modules', 'Gemfile', 'Gemfile.lock']
